# Generated by Django 5.1.3 on 2025-03-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactu_delete_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mail',
        ),
    ]
