# Generated by Django 5.1.3 on 2025-03-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactU',
        ),
    ]
